spring:
  datasource:
    url: jdbc:oracle:thin:@10.0.10.36:1521/XE
    username: learning
    password: inanc9889
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083
